### ISSUE TITLE
Documents tokens availabile in deb.json

### ISSUE THREAD

**Issue by solvingj** [mh-cbon/go-bin-deb#3]
The example features lines like this for which the tokens of !arch! and !name! get replaced: 
			"from": "build/!arch!/!name!"

It would be helpful to have a list of all the tokens that one can use from within the deb.json.

**Comment by solvingj** [comment]
Can you just confirm that !var! can be any of the variables passed in via CLI, OR any of the other JSON property names?

**Comment by mh-cbon** [comment]
> Can you just confirm that !var! can be any of the variables passed in via CLI, OR any of the other JSON property names?

no it is not. I added the doc https://github.com/mh-cbon/go-bin-deb#json-tokens
