### ISSUE TITLE
Receiving error "fakeroot, while creating message channels: Function not implemented"

### ISSUE THREAD

**Issue by solvingj** [mh-cbon/go-bin-deb#4]
Receiving error when running go-bin-deb on Ubuntu (Windows Subsystem for Linux). 

me@MY-DELL-03:~/go-github-release-test$ go-bin-deb generate --file deb-creation-data.json --version 0.0.1

> fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
exit status 1

Here is my deb-creation-data.json file.  

```javascript
{
	"name": "go-github-release-test",
	"maintainer": "ME <me@me.com>",
	"description": "Test of go-github-release process",
	"changelog-cmd":  "changelog debian --vars='{\"name\":\"!name!\"}'",
	"homepage": "http://github.com/solvingj/go-github-release-test",
	"files": [{
			"from": "build/!name!",
			"to": "/usr/bin",
			"base": "build",
			"fperm": "0755"
		}
	],
	"copyrights": [{
			"files": "*",
			"copyright": "2017 ME",
			"license": "MIT",
			"file": "LICENSE"
		}
	]
}
```

System Info
> Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

**Comment by solvingj** [comment]
I just ran on debian 8 and it works fine. seems to be an issue with running on WSL.  feel free to close if you don't want to support WSL.

**Comment by mh-cbon** [comment]
https://wiki.debian.org/FakeRoot

> fakeroot requires SYSV IPC to operate. 

unless i miss something, that should be the reason.
