### ISSUE TITLE
"changelog" tool is effectively a dependency

### ISSUE THREAD

**Issue by solvingj** [mh-cbon/go-bin-deb#5]
go-bin-deb seems to require changelog be installed.  If I blank out the changelog-command param, it says it can't generate the changelog, and if I remove the param altogether, it says changelog not found. I have been trying to get around these errors but still can't seem to build debs because of that, and the previous issue I opened. 

If changelog is effectively (or should be) a required dependency of the packaging tools, then it's probably reasonable to list that on this readme.

**Comment by mh-cbon** [comment]
as far as i can remember, debian packaging requires a changelog.

If nor `cat` nor `changelog` bin are available on your computer, 
you might want to use `changelog-file` key instead of `changelog-cmd`

**Comment by solvingj** [comment]
Ahh yes, this was the one.  I just thought it was a fine candidate to use/demonstrate deb package depenency.

**Comment by mh-cbon** [comment]
sure. Note now it will create an empty file.
